### ISSUE TITLE
iw3xport.exe missing from release

### ISSUE THREAD

**Issue by Dss0** [XLabsProject/iw3x-port#1]
it would probably be best to create a zip file with iw3x.dll and iw3xport.exe inside. Mod tools guide on xlabs.dev also needs to be updated to fetch the zip file then.
kthxbye

**Comment by diamante0018** [comment]
This seems to be resolved in the latest release however @Rackover can probably confirm this issue has been taken care of

**Comment by Rackover** [comment]
It has
